fix sccache

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -50,9 +50,18 @@ jobs:
           LINK: https://github.com/mozilla/sccache/releases/download
           SCCACHE_VERSION: 0.8.0
         run: |
-          SCCACHE_FILE=sccache-dist-v$SCCACHE_VERSION-x86_64-unknown-linux-musl
+          SCCACHE_FILE=sccache-dist-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl
           mkdir -p $HOME/.local/bin
-          curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
+          curl -L "${LINK}/v${SCCACHE_VERSION}/${SCCACHE_FILE}.tar.gz" -o "${SCCACHE_FILE}.tar.gz"
+          if [ $? -ne 0 ]; then
+            echo "Error downloading sccache."
+            exit 1
+          fi
+          tar xzf "${SCCACHE_FILE}.tar.gz"
+          if [ $? -ne 0 ]; then
+            echo "Error extracting sccache."
+            exit 1
+          fi
           mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
           echo "$HOME/.local/bin" >> $GITHUB_PATH          
       - name: Install sccache (macos-latest)
